name: Frontend Workflows

on:
    push:
        branches:
            - develop
            - main
    pull_request:
        branches:
            - develop
            - main

jobs:
    lint:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: frontend

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run lint
